<!-- ③ビュー -->
<!DOCTYPE html>
<html lang="ja">
<head>
	<meta charset="UTF-8">
	<title>test</title>
	<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
	<div class="container">
		<div class="card">
			<div class="card-body text-center">
				<h2 class="display-5">Arihito Framework</h2>
				<p>現在は <?= h(date('Y年m月d日H時i分s秒')); ?> です</p>
				<ul><li><a href='/phpinfo.php' class="btn btn-primary"><code>phpinfo()</code></a></ul>
				<hr>
				<p style="font-size:6px">This code is licensed under <a href="https://github.com/zonuexe/oiraphp">AGPL.</a></p>
			</div>
		</div>
	</div>
</body>
</html>


